// File: packages/src/index.js
// 组件库统一导出入口

// 导出组件
export { default as Chat } from "./components/Chat/index.vue";
export { default as Message } from "./components/Message/index.vue";
export { default as Composer } from "./components/Composer/index.vue";
export { default as Typing } from "./components/Typing/index.vue";
export { default as Thinking } from "./components/Thinking/index.vue";

export { default as SystemMessage } from "./components/SystemMessage/index.vue";
export { default as MessageStatus } from "./components/MessageStatus/index.vue";
export { default as File } from "./components/File/index.vue";
export { default as FileCard } from "./components/FileCard/index.vue";
export { default as Card } from "./components/Card/index.vue";
export { default as Search } from "./components/Search/index.vue";
export { default as Button } from "./components/Button/index.vue";
export { default as ButtonGroup } from "./components/ButtonGroup/index.vue";
export { default as Flex } from "./components/Flex/index.vue";
export { default as FlexItem } from "./components/FlexItem/index.vue";
export { default as Image } from "./components/Image/index.vue";
export { default as Checkbox } from "./components/Checkbox/index.vue";
export { default as CheckboxGroup } from "./components/CheckboxGroup/index.vue";
export { default as Input } from "./components/Input/index.vue";
export { default as RichEditor } from "./components/RichEditor/index.vue";
export { default as ChunkUploader } from "./components/ChunkUploader/index.vue";
export { default as Loading } from "./components/Loading/index.vue";
export { default as Waterfall } from "./components/Waterfall/index.vue";
export { default as SleepChart } from "./components/SleepChart/index.vue";
export { default as SleepRingChart } from "./components/SleepRingChart/index.vue";
export { default as HeartRateChart } from "./components/HeartRateChart/index.vue";
export { default as StepsChart } from "./components/StepsChart/index.vue";
export { default as BloodOxygenChart } from "./components/BloodOxygenChart/index.vue";
export { default as ActivityRingChart } from "./components/ActivityRingChart/index.vue";
export { default as WeeklyStatCard } from "./components/WeeklyStatCard/index.vue";
export { default as BodyWeightChart } from "./components/BodyWeightChart/index.vue";
export { default as BloodPressureChart } from "./components/BloodPressureChart/index.vue";
export { default as WaterIntakeChart } from "./components/WaterIntakeChart/index.vue";
export { default as CalorieBalanceChart } from "./components/CalorieBalanceChart/index.vue";
export { default as NutritionPieChart } from "./components/NutritionPieChart/index.vue";
export { default as BloodSugarChart } from "./components/BloodSugarChart/index.vue";
export { default as MoodTracker } from "./components/MoodTracker/index.vue";
export { default as MedicationReminder } from "./components/MedicationReminder/index.vue";
export { default as MenstrualCycleChart } from "./components/MenstrualCycleChart/index.vue";
export { default as TemperatureChart } from "./components/TemperatureChart/index.vue";
export { default as ExerciseDetailCard } from "./components/ExerciseDetailCard/index.vue";
export { default as HealthScoreCard } from "./components/HealthScoreCard/index.vue";
export { default as StressLevelChart } from "./components/StressLevelChart/index.vue";
export { default as HRVChart } from "./components/HRVChart/index.vue";
export { default as BreathingGuide } from "./components/BreathingGuide/index.vue";
export { default as BodyFatScale } from "./components/BodyFatScale/index.vue";
export { default as RunningDashboard } from "./components/RunningDashboard/index.vue";
export { default as FastingTimer } from "./components/FastingTimer/index.vue";
export { default as HabitTracker } from "./components/HabitTracker/index.vue";
export { default as FoodLogList } from "./components/FoodLogList/index.vue";
export { default as BodyMeasurements } from "./components/BodyMeasurements/index.vue";
export { default as WorkoutPaceChart } from "./components/WorkoutPaceChart/index.vue";
export { default as SportRouteView } from "./components/SportRouteView/index.vue";
export { default as ECGChart } from "./components/ECGChart/index.vue";
export { default as MarkdownRenderer } from "./components/MarkdownRenderer/index.vue";
export { default as MessageActions } from "./components/MessageActions/index.vue";
export { default as QuickReplies } from "./components/QuickReplies/index.vue";
export { default as ErrorMessage } from "./components/ErrorMessage/index.vue";
export { default as RegenerateButton } from "./components/RegenerateButton/index.vue";
export { default as FeedbackButton } from "./components/FeedbackButton/index.vue";
export { default as SwimmingChart } from "./components/SwimmingChart/index.vue";
export { default as CyclingChart } from "./components/CyclingChart/index.vue";
export { default as WorkoutCalendar } from "./components/WorkoutCalendar/index.vue";
export { default as SleepScoreCard } from "./components/SleepScoreCard/index.vue";
export { default as RespiratoryRateChart } from "./components/RespiratoryRateChart/index.vue";
export { default as PostureAnalysis } from "./components/PostureAnalysis/index.vue";
export { default as RehabProgress } from "./components/RehabProgress/index.vue";
export { default as LeaderboardCard } from "./components/LeaderboardCard/index.vue";
export { default as GoalProgressCard } from "./components/GoalProgressCard/index.vue";
export { default as SedentaryReminder } from "./components/SedentaryReminder/index.vue";
export { default as AudioWaveform } from "./components/AudioWaveform/index.vue";
export { default as FloatingButton } from "./components/FloatingButton/index.vue";
export { default as BackToTop } from "./components/BackToTop/index.vue";
export { default as StrengthTrainingChart } from "./components/StrengthTrainingChart/index.vue";
export { default as WorkoutZoneChart } from "./components/WorkoutZoneChart/index.vue";
export { default as AchievementBadge } from "./components/AchievementBadge/index.vue";
export { default as ChallengeCard } from "./components/ChallengeCard/index.vue";

// 导出 Hooks
export { useAutoScroll } from "./hooks/useAutoScroll.js";
export { useTypewriter } from "./hooks/useTypewriter.js";
export { useStreamingResponse } from "./hooks/useStreamingResponse.js";
